# Generated by Django 3.2.17 on 2023-02-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('capa', models.FileField(blank=True, null=True, upload_to='media')),
                ('slug', models.SlugField()),
                ('dt_cadastro', models.DateField(auto_now=True)),
            ],
        ),
    ]
