# Generated by Django 3.2.17 on 2023-02-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='capa',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
