# Generated by Django 3.2.17 on 2023-02-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0004_alter_serie_capa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.IntegerField()),
                ('slug', models.SlugField()),
                ('dt_cadastro', models.DateField(auto_now=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serie.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('dt_cadastro', models.DateField(auto_now=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serie.serie')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serie.temporada')),
            ],
        ),
    ]
