# Generated by Django 3.2.17 on 2023-02-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0005_episodio_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='video',
            field=models.FileField(default=1, upload_to='videos'),
            preserve_default=False,
        ),
    ]
